services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizapp-app
    environment:
      DB_URL: jdbc:mysql://db:3306/quizapp  # Use host.docker.internal to access localhost
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - quizapp-network
    depends_on:
      - db
    command: >
      sh -c "until mysql -h db -P 3306 -u root -proot -e 'SELECT 1'; do
        echo waiting for db;
        sleep 2;
      done;
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script
    networks:
      - quizapp-network

volumes:
  db_data: 
networks:
  quizapp-network:
