services:
  app:
    image: eugenievkim/cs-quizgame:latest
    container_name: quizapp-app
    environment:
      DB_URL: jdbc:mysql://db:3307/quizapp  # Use host.docker.internal to access localhost
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - quizapp-network
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script
    networks:
      - quizapp-network

volumes:
  db_data: 
networks:
  quizapp-network:
