services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizapp-app
    environment:
      DB_URL: jdbc:mysql://db:3306/quizapp  # Use host.docker.internal to access localhost
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8083:8080"
    networks:
      - quizapp-network
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizapp
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data: 
networks:
  quizapp-network:
