name: DockerRender

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        isMain:
          - ${{ contains(github.ref, 'main') }}
        java: [17]
    name: JDK${{ matrix.java }} ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: oracle
        
    - name: Build with Maven
      run: mvn clean package

    - name: Upload WAR file
      uses: actions/upload-artifact@v3
      with:
        name: quizapp
        path: target/quizapp-1.0-SNAPSHOT.war
        
    - name: Build Docker Images
      run: docker compose build

    - name: Run Tests
      run: |
        docker compose up -d
        sleep 10  # Adjust time as necessary
        docker compose logs  # View logs if needed
        # Add additional commands to verify container health
        docker compose down

    - name: Push Docker Images
      run: | 
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag docker.io/library/cs-quizgame-app "${{ secrets.DOCKER_USERNAME }}/cs-quizgame:latest"
        docker push "${{ secrets.DOCKER_USERNAME }}/cs-quizgame:latest"

    - name: Login to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} 
        RENDER_SERVICE_ID: srv-csis79dsvqrc73ej0htg
      run: |
       curl --request POST \
            --url https://api.render.com/v1/services/srv-csis79dsvqrc73ej0htg/deploys \
            --header 'accept: application/json' \
            --header 'authorization: Bearer rnd_K3nRXmT5B3wKY4bY63zSTtDNNIsd' \
            --header 'content-type: application/json' \
            --data '
        {
          "clearCache": "do_not_clear"
        }
        '
