name: Tomcat Smoke Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  LC_ALL: en_US.UTF-8

jobs:
  Tomcat_Test_Matrix:
    strategy:
      fail-fast: false
      matrix:
        isMain:
          - ${{ contains(github.ref, 'main') }}
        java: [17]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: oracle

    # Step to download jakarta.servlet-api.jar
    - name: Download Servlet API
      run: |
        curl -O https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar

   # Step to download org.json library
    - name: Download JSON Library
      run: |
        curl -O https://repo1.maven.org/maven2/org/json/json/20230227/json-20230227.jar

    # Step to download AspectJ
    - name: Download AspectJ Library
      run: |
        curl -O https://repo1.maven.org/maven2/org/aspectj/aspectjrt/1.9.19/aspectjrt-1.9.19.jar

    # Step to download Jakarta WebSocket API
    - name: Download Jakarta WebSocket API
      run: |
        curl -O https://repo1.maven.org/maven2/jakarta/websocket/jakarta.websocket-api/2.0.0/jakarta.websocket-api-2.0.0.jar

    # Compile Project Step with all libraries in Classpath
    - name: Compile Project
      run: |
        # Define the source directory, update if necessary
        SOURCE_DIR="WEB-INF/classes"  # Use your correct source directory here

        # Create build directory
        mkdir -p build

        # Determine classpath separator based on OS
        if [[ "$RUNNER_OS" == "Windows" ]]; then
            CP="jakarta.servlet-api-5.0.0.jar;json-20230227.jar;aspectjrt-1.9.19.jar;jakarta.websocket-api-2.0.0.jar"
        else
            CP="jakarta.servlet-api-5.0.0.jar:json-20230227.jar:aspectjrt-1.9.19.jar:jakarta.websocket-api-2.0.0.jar"
        fi

        # Compile using javac with the appropriate classpath
        find $SOURCE_DIR -name "*.java" -print0 | xargs -0 javac -cp "$CP" -d build
      shell: bash  # Use bash for all platforms
      
    - name: Set up Tomcat
      run: |
        curl -L -O https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
        # Verify the downloaded file type using file command in bash
        if [ "$(file apache-tomcat-9.0.74.tar.gz | grep 'gzip compressed data')" ]; then
          # Use 7z to extract the .tar.gz file if available, else consider using PowerShell extraction commands
          7z x apache-tomcat-9.0.74.tar.gz -aoa
          tar -xvf apache-tomcat-9.0.74.tar
          mv apache-tomcat-9.0.74 tomcat
        else
          echo "Download failed or file is not in gzip format"
          exit 1
        fi
      shell: bash
      env:
        CATALINA_HOME: ${{ github.workspace }}/tomcat

    - name: Deploy to Tomcat
      run: |
        # Check if JAVA_HOME is set for Windows, Ubuntu, or macOS
        if ($env:RUNNER_OS -eq "Windows") {
            if (-Not $env:JAVA_HOME) {
                Write-Host "JAVA_HOME is not set. Please set JAVA_HOME in your environment."
                exit 1
            }
        } elseif ($env:RUNNER_OS -eq "Linux") {
            if (-Not $env:JAVA_HOME) {
                Write-Host "JAVA_HOME is not set. Please set JAVA_HOME in your environment."
                exit 1
            }
        } elseif ($env:RUNNER_OS -eq "macOS") {
            if (-Not $env:JAVA_HOME) {
                Write-Host "JAVA_HOME is not set. Please set JAVA_HOME in your environment."
                exit 1
            }
        }
    
        # Proceed to remove the existing ROOT application if necessary
        $rootPath = "$env:CATALINA_HOME/webapps/ROOT"
    
        if ($env:RUNNER_OS -eq "Windows") {
            # Check if ROOT directory exists before removing
            if (Test-Path $rootPath) {
                Remove-Item -Recurse -Force $rootPath
            }
            # Create ROOT directory if it does not exist
            New-Item -ItemType Directory -Path $rootPath -Force
            Copy-Item -Recurse build\* $rootPath
            # Start Tomcat using cmd.exe
            Start-Process -NoNewWindow -File "cmd.exe" -ArgumentList "/c $env:CATALINA_HOME\bin\startup.bat"
        } elseif ($env:RUNNER_OS -eq "Linux") {
            # For Ubuntu (Linux)
            # Check if ROOT directory exists before removing
            if (Test-Path $rootPath) {
                Remove-Item -Recurse -Force $rootPath
            }
            # Create ROOT directory if it does not exist
            New-Item -ItemType Directory -Path $rootPath -Force
            cp -r build/* $rootPath
            # Start Tomcat
            bash "$env:CATALINA_HOME/bin/startup.sh"
        } elseif ($env:RUNNER_OS -eq "macOS") {
            # For macOS
            # Check if ROOT directory exists before removing
            if (Test-Path $rootPath) {
                Remove-Item -Recurse -Force $rootPath
            }
            # Create ROOT directory if it does not exist
            New-Item -ItemType Directory -Path $rootPath -Force
            cp -r build/* $rootPath
            
            # Check if startup.sh exists before trying to run it
            if (Test-Path "$env:CATALINA_HOME/bin/startup.sh") {
                # Start Tomcat for macOS
                bash "$env:CATALINA_HOME/bin/startup.sh"
            } else {
                Write-Host "Error: startup.sh not found at $env:CATALINA_HOME/bin/startup.sh"
                exit 1
            }
        }
      shell: pwsh
      env:
        LC_ALL: en_US.UTF-8
        CATALINA_HOME: /home/runner/work/CS-QuizGame/CS-QuizGame/tomcat

    - name: Run Smoke Test
      run: |
        sleep 20  # Allow time for Tomcat to start
        curl --fail http://localhost:8081/QuizApp || exit 1

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: JDK${{ matrix.java }}-${{ matrix.os }}-logs
        path: |
          $CATALINA_HOME/logs/*
        retention-days: 7
