name: Tomcat Smoke Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  LC_ALL: en_US.UTF-8

jobs:
  Tomcat_Test_Matrix:
    strategy:
      fail-fast: false
      matrix:
        isMain:
          - ${{ contains(github.ref, 'main') }}
        java: [17]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: oracle

    # Step to download jakarta.servlet-api.jar
    - name: Download Servlet API
      run: |
        curl -O https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar

   # Step to download org.json library
    - name: Download JSON Library
      run: |
        curl -O https://repo1.maven.org/maven2/org/json/json/20230227/json-20230227.jar

    # Step to download AspectJ
    - name: Download AspectJ Library
      run: |
        curl -O https://repo1.maven.org/maven2/org/aspectj/aspectjrt/1.9.19/aspectjrt-1.9.19.jar

    # Step to download Jakarta WebSocket API
    - name: Download Jakarta WebSocket API
      run: |
        curl -O https://repo1.maven.org/maven2/jakarta/websocket/jakarta.websocket-api/2.0.0/jakarta.websocket-api-2.0.0.jar

    # Compile Project Step with all libraries in Classpath
    - name: Compile Project
      run: |
        # Define the source directory, update if necessary
        SOURCE_DIR="WEB-INF/classes"  # Use your correct source directory here

        # Create build directory
        mkdir -p build

        # Determine classpath separator based on OS
        if [[ "$RUNNER_OS" == "Windows" ]]; then
            CP="jakarta.servlet-api-5.0.0.jar;json-20230227.jar;aspectjrt-1.9.19.jar;jakarta.websocket-api-2.0.0.jar"
        else
            CP="jakarta.servlet-api-5.0.0.jar:json-20230227.jar:aspectjrt-1.9.19.jar:jakarta.websocket-api-2.0.0.jar"
        fi

        # Compile using javac with the appropriate classpath
        find $SOURCE_DIR -name "*.java" -print0 | xargs -0 javac -cp "$CP" -d build
      shell: bash  # Use bash for all platforms
      
    - name: Set up Tomcat
      run: |
        curl -L -O https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
        # Verify the downloaded file type using file command in bash
        if [ "$(file apache-tomcat-9.0.74.tar.gz | grep 'gzip compressed data')" ]; then
          # Use 7z to extract the .tar.gz file if available, else consider using PowerShell extraction commands
          7z x apache-tomcat-9.0.74.tar.gz -aoa
          tar -xvf apache-tomcat-9.0.74.tar
          mv apache-tomcat-9.0.74 tomcat
        else
          echo "Download failed or file is not in gzip format"
          exit 1
        fi
      shell: bash
      env:
        CATALINA_HOME: ${{ github.workspace }}/tomcat

    - name: Deploy to Tomcat
      run: |
        # Define the path for the ROOT directory
        ROOT_PATH="$CATALINA_HOME/webapps/ROOT"
    
        # Function to create the ROOT directory
        create_root_directory() {
            if [ -d "$ROOT_PATH" ]; then
                echo "Removing existing ROOT directory..."
                rm -rf "$ROOT_PATH"
            fi
            
            echo "Creating ROOT directory..."
            mkdir -p "$ROOT_PATH"
            
            if [ ! -d "$ROOT_PATH" ]; then
                echo "Error: ROOT directory was not created successfully."
                exit 1
            fi
        }
    
        # Function to copy files to the ROOT directory
        copy_files() {
            echo "Copying build files to ROOT directory..."
            cp -R build/* "$ROOT_PATH"
        }
    
        # Detect the operating system and set commands accordingly
        case "$RUNNER_OS" in
            'Linux' | 'macOS')
                create_root_directory
                copy_files
                ;;
            'Windows')
                # Use PowerShell commands for Windows
                Write-Host "Removing existing ROOT directory..."
                if (Test-Path $ROOT_PATH) {
                    Remove-Item -Recurse -Force $ROOT_PATH
                }
                
                Write-Host "Creating ROOT directory..."
                New-Item -ItemType Directory -Path $ROOT_PATH -Force
                
                if (-Not (Test-Path $ROOT_PATH)) {
                    Write-Host "Error: ROOT directory was not created successfully."
                    exit 1
                }
                
                Write-Host "Copying build files to ROOT directory..."
                Copy-Item -Recurse build\* $ROOT_PATH
                ;;
            *)
                echo "Unsupported OS: $RUNNER_OS"
                exit 1
                ;;
        esac
    
        # Start Tomcat
        STARTUP_SCRIPT="$CATALINA_HOME/bin/startup.sh"
    
        echo "Starting Tomcat..."
        if [ -f "$STARTUP_SCRIPT" ]; then
            chmod +x "$STARTUP_SCRIPT"  # Ensure the script is executable
            bash "$STARTUP_SCRIPT"
        else
            echo "Error: startup.sh not found at $STARTUP_SCRIPT"
            exit 1
        fi
      shell: bash

    - name: Smoke Test for Tomcat
      run: |
        $url = "http://localhost:8081/QuizApp"
        echo "Waiting for Tomcat to start..."
        Start-Sleep -Seconds 20
    
        # Test the connection
        if ($env:RUNNER_OS -eq "Windows") {
            try {
                $response = Invoke-WebRequest -Uri $url -UseBasicP
                if ($response.StatusCode -eq 200) {
                    Write-Host "Smoke test passed: Tomcat is running and accessible."
                }
            } catch {
                Write-Host "Smoke test failed: Unable to connect to Tomcat. Error: $_"
                exit 1
            }
        } else {
            curl --fail "$url" || { Write-Host "Smoke test failed: Unable to connect to Tomcat."; exit 1; }
            Write-Host "Smoke test passed: Tomcat is running and accessible."
        }
      shell: pwsh

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: JDK${{ matrix.java }}-${{ matrix.os }}-logs
        path: |
          $CATALINA_HOME/logs/*
        retention-days: 7
